### ISSUE TITLE
Restructure Animation Component/System

### ISSUE THREAD

**Issue by paked** [paked/engi#4]
In the ECS paradigm components are designed to only store data, systems are supposed to manipulate this data. The current animation implementation has logic spread between the component and its related system.

**Comment by matiwinnetou** [comment]
Ok, having spend even more time with animation.go I can see what you were trying to achieve there.

The main issue is with increment() method which obviously processes data.

However, I am slowly coming to some conclusions how I would like this to look like:

For me
1. We should delete an actual Sprite type (legacy like you said)
2. We should seriously consider renaming Bounds to Sprite as bounds is form of a sprite. I am also fine to keep this Bounds if this is more natural for you. I am torn myself, as plain texture is also a kinda sprite.
3. We should provide Render method for Bounds (Sprite) and in future Draw if the code base is refactored to use Draw everywhere. I already have it working locally - but without camera
4. AnimationComponent apart from data it has (with some tweaks) should take as part of construction process - simply an array of Bounds. Array is already indexed. Later through methods or constructors we can pick which indexes are part of which frames. This gives us enormous flexibility, Spriteheet is today a very specific and concrete implementation. I can imagine other implementation based on some ripped sprite sheets from the internet, which do not conform to the contract (like Hero.png example). Since AnimationComponent does not have to know much about actual concrete Spritesheet type and implementation (which assumes too many things) we can simply provide other implementations of Sprite collections, like Spritemap.

To understand me better you can have a look at spritesheet I found on the internet:
http://www.spriters-resource.com/game_boy_advance/namcomuseum/sheet/22731/

This one is far from predictable patterns despite what it seems and Spritesheet freaks out on this even with my various tweaks. With such a spritemap the only option may be to manually define bounds and then form a number of array bounds from them that can be animated.

Thoughts?

PS.
I miss what is this dt, which is passed in update method and also what u,v mean in Region. Help appreciated.

**Comment by paked** [comment]
@matiwinnetou IMO `Region != Sprite`. A `Region` represents part of a `Texture`.

Yes. Regions should be `Renderable`, so we can stop [this](https://github.com/paked/engi/blob/master/level.go#L13-L25) kind of situation.

**Comment by paked** [comment]
Sure. Structure the `AnimationComponent` however you want. As long as no logic is performed on it. Logic should be performed on the `AnimationSystem`.

**Comment by paked** [comment]
`dt` is delta time, the change in time since the last frame was rendered... Useful for computing movement and stuff :)

**Comment by matiwinnetou** [comment]
Close please.
